### ISSUE TITLE
Resonance non riproduce l'audio in Quest Browser

### ISSUE THREAD

**Issue by AlbertoBoem** [CIMIL/SpatialAudioWebXR#9]

**Comment by AlbertoBoem** [comment]
@Samu01Tech Questa issue ha una priorita' LOW, lascia stare per ora.

**Comment by AlbertoBoem** [comment]
@Samu01Tech 

Ho testato su Chrome (Windows) e Firefox (Windows). L'audio e' riprodotto correttamente.

Questo e' quello che appare sulla console quando entro nella applicazione di Resonance

Uncaught (in promise) TypeError: t is undefined
    Aframe 31
    Webpack 9
[component.js:740:6](webpack://AFRAME/src/core/component.js)
Uncaught (in promise) TypeError: t is undefined
    Aframe 32
    Webpack 9
[component.js:740:6](webpack://AFRAME/src/core/component.js)
Uncaught (in promise) TypeError: t is undefined
    Aframe 33
    Webpack 9
[component.js:740:6](webpack://AFRAME/src/core/component.js)
Uncaught (in promise) TypeError: t is undefined
    Aframe 34
    Webpack 9
[component.js:740:6](webpack://AFRAME/src/core/component.js)
Uncaught (in promise) TypeError: t is undefined
    Aframe 35
    Webpack 9
[component.js:740:6](webpack://AFRAME/src/core/component.js)
Uncaught (in promise) TypeError: t is undefined
    Aframe 36
    Webpack 9
[component.js:740:6](webpack://AFRAME/src/core/component.js)
Uncaught (in promise) TypeError: t is undefined
    Aframe 37
    Webpack 9
[component.js:740:6](webpack://AFRAME/src/core/component.js)
Uncaught (in promise) TypeError: t is undefined
    Aframe 38
    Webpack 9
[component.js:740:6](webpack://AFRAME/src/core/component.js)
Uncaught (in promise) TypeError: t is undefined
    Aframe 39
    Webpack 9
[component.js:740:6](webpack://AFRAME/src/core/component.js)
Uncaught (in promise) TypeError: t is undefined
    Aframe 40
    Webpack 9
[component.js:740:6](webpack://AFRAME/src/core/component.js)
Uncaught (in promise) TypeError: t is undefined
    Aframe 41
    Webpack 9
[component.js:740:6](webpack://AFRAME/src/core/component.js)
Uncaught (in promise) TypeError: t is undefined
    Aframe 42
    Webpack 9
[component.js:740:6](webpack://AFRAME/src/core/component.js)
Uncaught (in promise) TypeError: t is undefined
    Aframe 43
    Webpack 9
[component.js:740:6](webpack://AFRAME/src/core/component.js)
Uncaught (in promise) TypeError: t is undefined
    Aframe 44
    Webpack 9
[component.js:740:6](webpack://AFRAME/src/core/component.js)
Uncaught (in promise) TypeError: t is undefined
    Aframe 45
    Webpack 9
[component.js:740:6](webpack://AFRAME/src/core/component.js)
Uncaught (in promise) TypeError: t is undefined
    Aframe 46
    Webpack 9
[component.js:740:6](webpack://AFRAME/src/core/component.js)
Uncaught (in promise) TypeError: t is undefined
    Aframe 47
    Webpack 9
[component.js:740:6](webpack://AFRAME/src/core/component.js)
Uncaught (in promise) TypeError: t is undefined
    Aframe 48
    Webpack 9
[component.js:740:6](webpack://AFRAME/src/core/component.js)
Uncaught (in promise) TypeError: t is undefined
    Aframe 49
    Webpack 9
[component.js:740:6](webpack://AFRAME/src/core/component.js)
Uncaught (in promise) TypeError: t is undefined
    Aframe 50
    Webpack 9
[component.js:740:6](webpack://AFRAME/src/core/component.js)
Uncaught (in promise) TypeError: t is undefined
    Aframe 51
    Webpack 9
[component.js:740:6](webpack://AFRAME/src/core/component.js)
Uncaught (in promise) TypeError: undefined has no properties
    Aframe 52
    Webpack 9
[component.js:740:6](webpack://AFRAME/src/core/component.js)
Uncaught (in promise) TypeError: undefined has no properties
    Aframe 53
    Webpack 9
[component.js:740:6](webpack://AFRAME/src/core/component.js)
Uncaught (in promise) TypeError: undefined has no properties
    Aframe 54
    Webpack 9
[component.js:740:6](webpack://AFRAME/src/core/component.js)
Uncaught (in promise) TypeError: undefined has no properties
    Aframe 55
    Webpack 9
[component.js:740:6](webpack://AFRAME/src/core/component.js)
Uncaught (in promise) TypeError: undefined has no properties
    Aframe 56
    Webpack 9
[component.js:740:6](webpack://AFRAME/src/core/component.js)
Uncaught (in promise) TypeError: undefined has no properties
    Aframe 57
    Webpack 9
[component.js:740:6](webpack://AFRAME/src/core/component.js)
Uncaught (in promise) TypeError: undefined has no properties
    Aframe 58
    Webpack 9
[component.js:740:6](webpack://AFRAME/src/core/component.js)
Uncaught (in promise) TypeError: undefined has no properties
    Aframe 59
    Webpack 9
[component.js:740:6](webpack://AFRAME/src/core/component.js)
Uncaught (in promise) TypeError: undefined has no properties
    Aframe 60
    Webpack 9
[component.js:740:6](webpack://AFRAME/src/core/component.js)
Uncaught (in promise) TypeError: undefined has no properties
    Aframe 61
    Webpack 9
[component.js:740:6](webpack://AFRAME/src/core/component.js)
Uncaught (in promise) TypeError: undefined has no properties
    Aframe 62
    Webpack 9
[component.js:740:6](webpack://AFRAME/src/core/component.js)
Uncaught (in promise) TypeError: undefined has no properties
    Aframe 63
    Webpack 9
[component.js:740:6](webpack://AFRAME/src/core/component.js)
Uncaught (in promise) TypeError: undefined has no properties
    Aframe 64
    Webpack 9
[component.js:740:6](webpack://AFRAME/src/core/component.js)
Uncaught (in promise) TypeError: undefined has no properties
    Aframe 65
    Webpack 9
[component.js:740:6](webpack://AFRAME/src/core/component.js)
Uncaught (in promise) TypeError: undefined has no properties
    Aframe 66
    Webpack 9
[component.js:740:6](webpack://AFRAME/src/core/component.js)
Uncaught (in promise) TypeError: undefined has no properties
    Aframe 67
    Webpack 9
[component.js:740:6](webpack://AFRAME/src/core/component.js)
Uncaught (in promise) TypeError: undefined has no properties
    Aframe 68
    Webpack 9
[component.js:740:6](webpack://AFRAME/src/core/component.js)
Uncaught (in promise) TypeError: undefined has no properties
    Aframe 69
    Webpack 9
[component.js:740:6](webpack://AFRAME/src/core/component.js)
Uncaught (in promise) TypeError: undefined has no properties
    Aframe 70
    Webpack 9
[component.js:740:6](webpack://AFRAME/src/core/component.js)
Uncaught (in promise) TypeError: undefined has no properties
    Aframe 71
    Webpack 9
[component.js:740:6](webpack://AFRAME/src/core/component.js)
Uncaught (in promise) TypeError: undefined has no properties
    Aframe 72
    Webpack 9
[component.js:740:6](webpack://AFRAME/src/core/component.js)
Uncaught (in promise) TypeError: undefined has no properties
    Aframe 73
    Webpack 9
[component.js:740:6](webpack://AFRAME/src/core/component.js)
Uncaught (in promise) TypeError: undefined has no properties
    Aframe 74
    Webpack 9
[component.js:740:6](webpack://AFRAME/src/core/component.js)
Uncaught (in promise) TypeError: undefined has no properties
    Aframe 75
    Webpack 9
[component.js:740:6](webpack://AFRAME/src/core/component.js)
Uncaught (in promise) TypeError: undefined has no properties
    Aframe 76
    Webpack 9
[component.js:740:6](webpack://AFRAME/src/core/component.js)
Uncaught (in promise) TypeError: undefined has no properties
    Aframe 77
    Webpack 9
[component.js:740:6](webpack://AFRAME/src/core/component.js)
Uncaught (in promise) TypeError: undefined has no properties
    Aframe 78
    Webpack 9
[component.js:740:6](webpack://AFRAME/src/core/component.js)
Uncaught (in promise) TypeError: undefined has no properties
    Aframe 79
    Webpack 9
[component.js:740:6](webpack://AFRAME/src/core/component.js)
Uncaught (in promise) TypeError: undefined has no properties
    Aframe 80
    Webpack 9
[component.js:740:6](webpack://AFRAME/src/core/component.js)
Uncaught (in promise) TypeError: undefined has no properties
    Aframe 81
    Webpack 9
[component.js:740:6](webpack://AFRAME/src/core/component.js)
Uncaught (in promise) TypeError: undefined has no properties
    Aframe 82
    Webpack 9
[component.js:740:6](webpack://AFRAME/src/core/component.js)
Uncaught (in promise) TypeError: undefined has no properties
    Aframe 83
    Webpack 9
[component.js:740:6](webpack://AFRAME/src/core/component.js)
Uncaught (in promise) TypeError: undefined has no properties
    Aframe 84
    Webpack 9
[component.js:740:6](webpack://AFRAME/src/core/component.js)
Uncaught (in promise) TypeError: undefined has no properties
    Aframe 85
    Webpack 9
[component.js:740:6](webpack://AFRAME/src/core/component.js)
Uncaught (in promise) TypeError: undefined has no properties
    Aframe 86
    Webpack 9
[component.js:740:6](webpack://AFRAME/src/core/component.js)
Uncaught (in promise) TypeError: undefined has no properties
    Aframe 87
    Webpack 9
[component.js:740:6](webpack://AFRAME/src/core/component.js)
Uncaught (in promise) TypeError: undefined has no properties
    Aframe 88
    Webpack 9
[component.js:740:6](webpack://AFRAME/src/core/component.js)
Uncaught (in promise) TypeError: undefined has no properties
    Aframe 89
    Webpack 9
[component.js:740:6](webpack://AFRAME/src/core/component.js)
Uncaught (in promise) TypeError: undefined has no properties
    Aframe 90
    Webpack 9
[component.js:740:6](webpack://AFRAME/src/core/component.js)
Uncaught (in promise) TypeError: undefined has no properties
    Aframe 91
    Webpack 9
[component.js:740:6](webpack://AFRAME/src/core/component.js)
Uncaught (in promise) TypeError: undefined has no properties
    Aframe 92
    Webpack 9
[component.js:740:6](webpack://AFRAME/src/core/component.js)
Uncaught (in promise) TypeError: undefined has no properties
    Aframe 93
    Webpack 9
[component.js:740:6](webpack://AFRAME/src/core/component.js)
[vite] connected. [client.ts:150:14](https://192.168.56.1:5173/@vite/client.ts)

È stato impedito a un AudioContext di avviarsi automaticamente. Deve essere creato o deve riprendere dopo un azione dell’utente sulla pagina.

**Comment by AlbertoBoem** [comment]
Quando premo il pulsante START ricevo questo errore:

Uncaught TypeError: s.emit is not a function
    Aframe 6
    playFromRandomSpeaker main.js:53
    Aframe 3
    init main.js:142
    Aframe 44
    Webpack 7
[aframe-state-component.min.js:1:10042](https://unpkg.com/aframe-state-component@7.0.0/dist/aframe-state-component.min.js)
Uncaught TypeError: s.emit is not a function
    Aframe 6
    init main.js:142
    Aframe 44
    Webpack 7
[aframe-state-component.min.js:1:10042](https://unpkg.com/aframe-state-component@7.0.0/dist/aframe-state-component.min.js)
Uncaught TypeError: s.emit is not a function
    Aframe 6
    playFromRandomSpeaker main.js:58
    setTimeout handler*playFromRandomSpeaker main.js:56
    Aframe 3
    init main.js:142
    Aframe 44
    Webpack 7
[aframe-state-component.min.js:1:10042](https://unpkg.com/aframe-state-component@7.0.0/dist/aframe-state-component.min.js)
Uncaught TypeError: s.emit is not a function
    Aframe 6
    playFromRandomSpeaker main.js:61
    setTimeout handler*playFromRandomSpeaker main.js:56
    Aframe 3
    init main.js:142
    Aframe 44
    Webpack 7
[aframe-state-component.min.js:1:10042](https://unpkg.com/aframe-state-component@7.0.0/dist/aframe-state-component.min.js)

​

**Comment by AlbertoBoem** [comment]
I debugger di Firefox (a differenza di Chrome) mi da questo messaggio all'avvio di Omnitone

È stato impedito a un AudioContext di avviarsi automaticamente. Deve essere creato o deve riprendere dopo un azione dell’utente sulla pagina. [resonance-audio-room.js:39:24](webpack://aframe-resonance-audio-component/src/resonance-audio-room.js)

[Omnitone] FOARenderer: Initializing... (mode: ambisonic) (@1117.00ms) [resonance-audio.js:4077:21](webpack://aframe-resonance-audio-component/node_modules/resonance-audio/build/resonance-audio.js)

È stato impedito a un AudioContext di avviarsi automaticamente. Deve essere creato o deve riprendere dopo un azione dell’utente sulla pagina. [resonance-audio-room.js:39:24](webpack://aframe-resonance-audio-component/src/resonance-audio-room.js)

[Omnitone] FOARenderer: Initializing... (mode: ambisonic) (@1151.00ms)

**Comment by AlbertoBoem** [comment]
https://stackoverflow.com/questions/55026293/google-chrome-javascript-issue-in-getting-user-audio-the-audiocontext-was-not

getAudioContext().resume();

**Comment by Samu01Tech** [comment]
Interessante, anche se in teoria l'interazione c'è premendo il tasto start, ma è un buon punto di partenza per capire cosa non va

**Comment by AlbertoBoem** [comment]
Ho provato cosi, ho riaggiunto il file audio 

```html
<a-assets>
        <audio id="track" src="./white-noise-impulse.wav"></audio>
</a-assets>
```

poi, ho cambiato di conseguenza il riferimento 

```js
resonance-audio-src="src: {{track}}; autoplay: true; loop: true; gain: 10"
```

quando premo START, l'audio inizia ad esssere riprodotto correttamente sul browser del Quest


funziona ugualmente cosi, anche se va in loop automatico

```js
resonance-audio-src="src: {{track}}; autoplay: false; loop: false; gain: 10"
```

**Comment by AlbertoBoem** [comment]
Questo mi fa pensare che forse il problema e' come il file viene inizializzato e se viene inizializzato correttamente.
Non vorrei che ci fosse qualche modalita' di inizializzazione dell'audio che va in conflitto con il browser del quest.

Forse sarebbe da avviare la parte audio, magari con un volume 0 all'entrata e poi messa in pausa e ripresa poi?

**Comment by AlbertoBoem** [comment]
Quando premo START (in ogni caso) ottengo questi due errori:

rame-state-component.min.js:1 Uncaught TypeError: s.emit is not a function
    at n.renderItems (aframe-state-component.min.js:1:10042)
    at n.<anonymous> (aframe-state-component.min.js:1:9530)
    at n.onStateUpdate (aframe-state-component.min.js:1:12895)
    at i.<anonymous> (aframe-state-component.min.js:1:4244)
    at v.<anonymous> (aframe-state-component.min.js:1:5059)
    at v.emit (a-node.js:293:10)
    at Object.playFromRandomSpeaker (main.js:53:24)
    at i.<anonymous> (aframe-state-component.min.js:1:3570)
    at v.<anonymous> (aframe-state-component.min.js:1:5059)
    at v.emit (a-node.js:293:10)
renderItems @ aframe-state-component.min.js:1
(anonymous) @ aframe-state-component.min.js:1
onStateUpdate @ aframe-state-component.min.js:1
(anonymous) @ aframe-state-component.min.js:1
(anonymous) @ aframe-state-component.min.js:1
emit @ a-node.js:293
playFromRandomSpeaker @ main.js:53
(anonymous) @ aframe-state-component.min.js:1
(anonymous) @ aframe-state-component.min.js:1
emit @ a-node.js:293
(anonymous) @ main.js:143
emit @ a-node.js:293
twoWayEmit @ cursor.js:502
onCursorUp @ cursor.js:337
(anonymous) @ bind.js:12
emit @ a-node.js:293
e.exports.onButtonEvent @ tracked-controls.js:236
onButtonUp @ oculus-touch-controls.js:215
emit @ a-node.js:293
handlePress @ tracked-controls-webxr.js:182
handleButton @ tracked-controls-webxr.js:130
updateButtons @ tracked-controls-webxr.js:115
tick @ tracked-controls-webxr.js:81
tick @ a-scene.js:701
render @ a-scene.js:747
(anonymous) @ bind.js:12
(anonymous) @ three.module.js:28189
r @ three.module.js:13400
XRRequestFrame (async)
r @ three.module.js:13402
XRRequestFrame (async)
r @ three.module.js:13402
XRRequestFrame (async)
r @ three.module.js:13402
XRRequestFrame (async)
r @ three.module.js:13402
XRRequestFrame (async)
r @ three.module.js:13402
XRRequestFrame (async)
r @ three.module.js:13402
XRRequestFrame (async)
r @ three.module.js:13402
XRRequestFrame (async)
r @ three.module.js:13402
XRRequestFrame (async)
r @ three.module.js:13402
XRRequestFrame (async)
r @ three.module.js:13402
XRRequestFrame (async)
r @ three.module.js:13402
XRRequestFrame (async)
r @ three.module.js:13402
XRRequestFrame (async)
r @ three.module.js:13402
XRRequestFrame (async)
r @ three.module.js:13402
XRRequestFrame (async)
r @ three.module.js:13402
XRRequestFrame (async)
r @ three.module.js:13402
XRRequestFrame (async)
r @ three.module.js:13402
XRRequestFrame (async)
r @ three.module.js:13402
XRRequestFrame (async)
r @ three.module.js:13402
XRRequestFrame (async)
r @ three.module.js:13402
XRRequestFrame (async)
r @ three.module.js:13402
XRRequestFrame (async)
r @ three.module.js:13402
XRRequestFrame (async)
r @ three.module.js:13402
XRRequestFrame (async)
r @ three.module.js:13402
XRRequestFrame (async)
r @ three.module.js:13402
XRRequestFrame (async)
r @ three.module.js:13402
XRRequestFrame (async)
r @ three.module.js:13402
XRRequestFrame (async)
r @ three.module.js:13402
XRRequestFrame (async)
r @ three.module.js:13402
XRRequestFrame (async)
r @ three.module.js:13402
XRRequestFrame (async)
r @ three.module.js:13402
XRRequestFrame (async)
r @ three.module.js:13402
aframe-state-component.min.js:1 Uncaught TypeError: s.emit is not a function
    at n.renderItems (aframe-state-component.min.js:1:10042)
    at n.<anonymous> (aframe-state-component.min.js:1:9530)
    at n.onStateUpdate (aframe-state-component.min.js:1:12895)
    at i.<anonymous> (aframe-state-component.min.js:1:4244)
    at v.<anonymous> (aframe-state-component.min.js:1:5059)
    at v.emit (a-node.js:293:10)
    at a.<anonymous> (main.js:143:24)
    at a.emit (a-node.js:293:10)
    at n.twoWayEmit (cursor.js:502:19)
    at n.onCursorUp (cursor.js:337:12)

e subito dopo questi due:

rame-state-component.min.js:1 Uncaught TypeError: s.emit is not a function
    at n.renderItems (aframe-state-component.min.js:1:10042)
    at n.<anonymous> (aframe-state-component.min.js:1:9530)
    at n.onStateUpdate (aframe-state-component.min.js:1:12895)
    at i.<anonymous> (aframe-state-component.min.js:1:4244)
    at v.<anonymous> (aframe-state-component.min.js:1:5059)
    at v.emit (a-node.js:293:10)
    at main.js:58:26
renderItems @ aframe-state-component.min.js:1
(anonymous) @ aframe-state-component.min.js:1
onStateUpdate @ aframe-state-component.min.js:1
(anonymous) @ aframe-state-component.min.js:1
(anonymous) @ aframe-state-component.min.js:1
emit @ a-node.js:293
(anonymous) @ main.js:58
setTimeout (async)
playFromRandomSpeaker @ main.js:56
(anonymous) @ aframe-state-component.min.js:1
(anonymous) @ aframe-state-component.min.js:1
emit @ a-node.js:293
(anonymous) @ main.js:143
emit @ a-node.js:293
twoWayEmit @ cursor.js:502
onCursorUp @ cursor.js:337
(anonymous) @ bind.js:12
emit @ a-node.js:293
e.exports.onButtonEvent @ tracked-controls.js:236
onButtonUp @ oculus-touch-controls.js:215
emit @ a-node.js:293
handlePress @ tracked-controls-webxr.js:182
handleButton @ tracked-controls-webxr.js:130
updateButtons @ tracked-controls-webxr.js:115
tick @ tracked-controls-webxr.js:81
tick @ a-scene.js:701
render @ a-scene.js:747
(anonymous) @ bind.js:12
(anonymous) @ three.module.js:28189
r @ three.module.js:13400
XRRequestFrame (async)
r @ three.module.js:13402
XRRequestFrame (async)
r @ three.module.js:13402
XRRequestFrame (async)
r @ three.module.js:13402
XRRequestFrame (async)
r @ three.module.js:13402
XRRequestFrame (async)
r @ three.module.js:13402
XRRequestFrame (async)
r @ three.module.js:13402
XRRequestFrame (async)
r @ three.module.js:13402
XRRequestFrame (async)
r @ three.module.js:13402
XRRequestFrame (async)
r @ three.module.js:13402
XRRequestFrame (async)
r @ three.module.js:13402
XRRequestFrame (async)
r @ three.module.js:13402
XRRequestFrame (async)
r @ three.module.js:13402
XRRequestFrame (async)
r @ three.module.js:13402
XRRequestFrame (async)
r @ three.module.js:13402
XRRequestFrame (async)
r @ three.module.js:13402
XRRequestFrame (async)
r @ three.module.js:13402
XRRequestFrame (async)
r @ three.module.js:13402
XRRequestFrame (async)
r @ three.module.js:13402
XRRequestFrame (async)
r @ three.module.js:13402
XRRequestFrame (async)
r @ three.module.js:13402
XRRequestFrame (async)
r @ three.module.js:13402
XRRequestFrame (async)
r @ three.module.js:13402
XRRequestFrame (async)
r @ three.module.js:13402
XRRequestFrame (async)
r @ three.module.js:13402
XRRequestFrame (async)
r @ three.module.js:13402
XRRequestFrame (async)
r @ three.module.js:13402
XRRequestFrame (async)
r @ three.module.js:13402
XRRequestFrame (async)
r @ three.module.js:13402
XRRequestFrame (async)
r @ three.module.js:13402
XRRequestFrame (async)
r @ three.module.js:13402
XRRequestFrame (async)
r @ three.module.js:13402
aframe-state-component.min.js:1 Uncaught TypeError: s.emit is not a function
    at n.renderItems (aframe-state-component.min.js:1:10042)
    at n.<anonymous> (aframe-state-component.min.js:1:9530)
    at n.onStateUpdate (aframe-state-component.min.js:1:12895)
    at i.<anonymous> (aframe-state-component.min.js:1:4244)
    at v.<anonymous> (aframe-state-component.min.js:1:5059)
    at v.emit (a-node.js:293:10)
    at main.js:61:26
r

**Comment by AlbertoBoem** [comment]
Stavo pensando, e se il problema fosse dovuto a questo? 
https://developer.chrome.com/blog/autoplay

Non si potrebbe inserire uno step dove l'utente preme il pulsante.
Magari:
- Appare Messaggio "Ready?"
- Poi "Press here" (utente deve puntare e premere nel cerchio dove ci sara' il countdown)
- "Look here"
- parte il countown
- audio play

?

**Comment by AlbertoBoem** [comment]
[192.168.1.3-1734026791976.log](https://github.com/user-attachments/files/18115765/192.168.1.3-1734026791976.log)

**Comment by AlbertoBoem** [comment]
resonance-audio-room.js:39 The AudioContext was not allowed to start. It must be resumed (or created) after a user gesture on the page. https://goo.gl/7K7WLu

**Comment by AlbertoBoem** [comment]
oculus-touch-controls.js:231 [Violation] Added non-passive event listener to a scroll-blocking 'touchstart' event. Consider marking event handler as 'passive' to make the page more responsive. See https://www.chromestatus.com/feature/5745543795965952

oculus-touch-controls.js:231 [Violation] Added non-passive event listener to a scroll-blocking 'touchstart' event. Consider marking event handler as 'passive' to make the page more responsive. See https://www.chromestatus.com/feature/5745543795965952

**Comment by AlbertoBoem** [comment]
The AudioContext was not allowed to start. It must be resumed (or created) after a user gesture on the page.

Il problema e' qui:

`resonance-audio-room.js`

```
init () {
    // Initialize the audio context and connect with Resonance.
    this.audioContext = new AudioContext()
```


Una soluzione potrebbe essere una cosa del genere:

`document.getElementById('startButton').addEventListener('click', 
     function() { var audioContext = new AudioContext();
}):`

**Comment by AlbertoBoem** [comment]
`branch /audioContextStart`

- Anche da web browser su PC (edge)

```
Uncaught TypeError: Cannot read properties of null (reading 'play')
    at Object.playFromRandomSpeaker (loop.js:24:43)
    at i.<anonymous> (aframe-state-component.min.js:1:3619)
    at v.<anonymous> (aframe-state-component.min.js:1:5108)
    at v.emit (a-node.js:306:10)
    at Object.removeBaseline (baseline.js:33:20)
    at i.<anonymous> (aframe-state-component.min.js:1:3619)
    at v.<anonymous> (aframe-state-component.min.js:1:5108)
    at v.emit (a-node.js:306:10)
    at Object.checkIfIntersected (baseline.js:55:24)
    at i.<anonymous> (aframe-state-component.min.js:1:3619)
```

- Secondo me il problema piu' grosso e' qui:

`The AudioContext was not allowed to start. It must be resumed (or created) after a user gesture on the page. (resonance-audio-room.js:39) `

```
// Initialize the audio context and connect with Resonance.
    this.audioContext = new AudioContext()
    this.resonanceAudioScene = new ResonanceAudio(this.audioContext)
    this.resonanceAudioScene.output.conne
```
